/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_comment_token1 = 1,
  aux_sym__line_token1 = 2,
  anon_sym_LBRACK = 3,
  anon_sym_RBRACK = 4,
  anon_sym_SLASH = 5,
  aux_sym_glob_token1 = 6,
  sym_wildcard = 7,
  sym_character_escape = 8,
  anon_sym_LBRACE = 9,
  anon_sym_COMMA = 10,
  anon_sym_RBRACE = 11,
  anon_sym_DOT_DOT = 12,
  aux_sym_integer_range_token1 = 13,
  sym_character = 14,
  anon_sym_DASH = 15,
  aux_sym_character_range_token1 = 16,
  anon_sym_BANG = 17,
  aux_sym_character_choice_token1 = 18,
  anon_sym_EQ = 19,
  aux_sym_pair_token1 = 20,
  sym_property = 21,
  sym_string = 22,
  sym__end_of_file = 23,
  sym__integer_range_start = 24,
  sym_editorconfig = 25,
  sym_comment = 26,
  sym__line = 27,
  sym_preamble = 28,
  sym_section = 29,
  sym_header = 30,
  sym_glob = 31,
  sym_brace_expansion = 32,
  sym_integer_range = 33,
  sym_character_range = 34,
  sym_character_choice = 35,
  sym_pair = 36,
  sym__eol = 37,
  aux_sym_editorconfig_repeat1 = 38,
  aux_sym_preamble_repeat1 = 39,
  aux_sym_glob_repeat1 = 40,
  aux_sym_brace_expansion_repeat1 = 41,
  aux_sym_character_choice_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym__line_token1] = "_line_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_SLASH] = "/",
  [aux_sym_glob_token1] = "glob_token1",
  [sym_wildcard] = "wildcard",
  [sym_character_escape] = "character_escape",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOT_DOT] = "..",
  [aux_sym_integer_range_token1] = "integer",
  [sym_character] = "character",
  [anon_sym_DASH] = "-",
  [aux_sym_character_range_token1] = "character",
  [anon_sym_BANG] = "!",
  [aux_sym_character_choice_token1] = "character_escape",
  [anon_sym_EQ] = "=",
  [aux_sym_pair_token1] = "pair_token1",
  [sym_property] = "property",
  [sym_string] = "string",
  [sym__end_of_file] = "_end_of_file",
  [sym__integer_range_start] = "integer",
  [sym_editorconfig] = "editorconfig",
  [sym_comment] = "comment",
  [sym__line] = "_line",
  [sym_preamble] = "preamble",
  [sym_section] = "section",
  [sym_header] = "header",
  [sym_glob] = "glob",
  [sym_brace_expansion] = "brace_expansion",
  [sym_integer_range] = "integer_range",
  [sym_character_range] = "character_range",
  [sym_character_choice] = "character_choice",
  [sym_pair] = "pair",
  [sym__eol] = "_eol",
  [aux_sym_editorconfig_repeat1] = "editorconfig_repeat1",
  [aux_sym_preamble_repeat1] = "preamble_repeat1",
  [aux_sym_glob_repeat1] = "glob_repeat1",
  [aux_sym_brace_expansion_repeat1] = "brace_expansion_repeat1",
  [aux_sym_character_choice_repeat1] = "character_choice_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym__line_token1] = aux_sym__line_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [aux_sym_glob_token1] = aux_sym_glob_token1,
  [sym_wildcard] = sym_wildcard,
  [sym_character_escape] = sym_character_escape,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [aux_sym_integer_range_token1] = sym__integer_range_start,
  [sym_character] = sym_character,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_character_range_token1] = sym_character,
  [anon_sym_BANG] = anon_sym_BANG,
  [aux_sym_character_choice_token1] = sym_character_escape,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_pair_token1] = aux_sym_pair_token1,
  [sym_property] = sym_property,
  [sym_string] = sym_string,
  [sym__end_of_file] = sym__end_of_file,
  [sym__integer_range_start] = sym__integer_range_start,
  [sym_editorconfig] = sym_editorconfig,
  [sym_comment] = sym_comment,
  [sym__line] = sym__line,
  [sym_preamble] = sym_preamble,
  [sym_section] = sym_section,
  [sym_header] = sym_header,
  [sym_glob] = sym_glob,
  [sym_brace_expansion] = sym_brace_expansion,
  [sym_integer_range] = sym_integer_range,
  [sym_character_range] = sym_character_range,
  [sym_character_choice] = sym_character_choice,
  [sym_pair] = sym_pair,
  [sym__eol] = sym__eol,
  [aux_sym_editorconfig_repeat1] = aux_sym_editorconfig_repeat1,
  [aux_sym_preamble_repeat1] = aux_sym_preamble_repeat1,
  [aux_sym_glob_repeat1] = aux_sym_glob_repeat1,
  [aux_sym_brace_expansion_repeat1] = aux_sym_brace_expansion_repeat1,
  [aux_sym_character_choice_repeat1] = aux_sym_character_choice_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_glob_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [sym_character_escape] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_integer_range_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_character] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_character_range_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_character_choice_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_pair_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__end_of_file] = {
    .visible = false,
    .named = true,
  },
  [sym__integer_range_start] = {
    .visible = true,
    .named = true,
  },
  [sym_editorconfig] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_preamble] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_glob] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_expansion] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_range] = {
    .visible = true,
    .named = true,
  },
  [sym_character_range] = {
    .visible = true,
    .named = true,
  },
  [sym_character_choice] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_editorconfig_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_preamble_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_glob_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_brace_expansion_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_character_choice_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_end = 1,
  field_key = 2,
  field_start = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_end] = "end",
  [field_key] = "key",
  [field_start] = "start",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
  [1] =
    {field_end, 2},
    {field_start, 0},
  [3] =
    {field_key, 0},
    {field_value, 3},
  [5] =
    {field_end, 3},
    {field_start, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 7,
  [10] = 8,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 18,
  [22] = 19,
  [23] = 17,
  [24] = 16,
  [25] = 20,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 31,
  [38] = 38,
  [39] = 30,
  [40] = 32,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 41,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 54,
  [56] = 56,
  [57] = 57,
  [58] = 50,
  [59] = 57,
};

static const TSCharacterRange aux_sym_glob_token1_character_set_1[] = {
  {0, '\t'}, {0x0b, '\f'}, {0x0e, ')'}, {'+', '.'}, {'0', '>'}, {'@', 'Z'}, {'\\', '\\'}, {'^', 'z'},
  {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '\n', 19,
        '\r', 1,
        '!', 40,
        '*', 28,
        ',', 31,
        '-', 38,
        '.', 9,
        '/', 22,
        '=', 42,
        '?', 27,
        '[', 20,
        '\\', 7,
        ']', 21,
        '{', 30,
        '}', 32,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(15);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(45);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(35);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '*', 28,
        ',', 31,
        '/', 22,
        '?', 27,
        '[', 20,
        '\\', 26,
        '{', 30,
        '}', 32,
        '\t', 24,
        ' ', 24,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(23);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '*', 28,
        '/', 22,
        '?', 27,
        '[', 20,
        '\\', 26,
        ']', 21,
        '{', 30,
        '\t', 25,
        ' ', 25,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '}') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(37);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(35);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '-', 41,
        '\\', 29,
        ']', 29,
        '*', 29,
        ',', 29,
        '?', 29,
        '[', 29,
        '{', 29,
        '}', 29,
      );
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(33);
      END_STATE();
    case 10:
      if (lookahead == '\\') ADVANCE(37);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(35);
      END_STATE();
    case 11:
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '=') ADVANCE(44);
      END_STATE();
    case 12:
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(45);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(39);
      END_STATE();
    case 15:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '\n', 19,
        '\r', 1,
        '*', 28,
        ',', 31,
        '/', 22,
        '=', 42,
        '?', 27,
        '[', 20,
        '\\', 7,
        ']', 21,
        '{', 30,
        '}', 32,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(15);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(18);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(16);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(18);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '=') ADVANCE(44);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym__line_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_glob_token1);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_glob_token1);
      if (lookahead == ',') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if ((!eof && set_contains(aux_sym_glob_token1_character_set_1, 10, lookahead))) ADVANCE(23);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_glob_token1);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      if ((!eof && set_contains(aux_sym_glob_token1_character_set_1, 10, lookahead))) ADVANCE(23);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_glob_token1);
      if (lookahead == '*' ||
          lookahead == ',' ||
          lookahead == '?' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_wildcard);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_wildcard);
      if (lookahead == '*') ADVANCE(27);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_character_escape);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_integer_range_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_character);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_character);
      if (lookahead == '\\') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_character);
      if (lookahead == '-' ||
          lookahead == '\\' ||
          lookahead == ']') ADVANCE(41);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_character_range_token1);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_character_choice_token1);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_pair_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_property);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '=') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(45);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 4, .external_lex_state = 2},
  [3] = {.lex_state = 4, .external_lex_state = 2},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 16},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 16},
  [15] = {.lex_state = 16},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 16},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 16},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 10},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 10},
  [42] = {.lex_state = 2, .external_lex_state = 3},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 10},
  [45] = {.lex_state = 0, .external_lex_state = 3},
  [46] = {.lex_state = 0, .external_lex_state = 3},
  [47] = {.lex_state = 0, .external_lex_state = 3},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 43},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 14},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 8},
  [59] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
    [aux_sym__line_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_wildcard] = ACTIONS(1),
    [sym_character_escape] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [aux_sym_character_choice_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym__end_of_file] = ACTIONS(1),
    [sym__integer_range_start] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_editorconfig] = STATE(56),
    [sym_comment] = STATE(12),
    [sym__line] = STATE(12),
    [sym_preamble] = STATE(36),
    [sym_section] = STATE(28),
    [sym_header] = STATE(13),
    [sym_pair] = STATE(12),
    [aux_sym_editorconfig_repeat1] = STATE(28),
    [aux_sym_preamble_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_comment_token1] = ACTIONS(5),
    [aux_sym__line_token1] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_property] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_COMMA,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    ACTIONS(23), 1,
      sym__integer_range_start,
    STATE(5), 2,
      sym_glob,
      aux_sym_brace_expansion_repeat1,
    ACTIONS(15), 4,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
    STATE(7), 4,
      sym_brace_expansion,
      sym_integer_range,
      sym_character_choice,
      aux_sym_glob_repeat1,
  [32] = 8,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_COMMA,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    ACTIONS(29), 1,
      sym__integer_range_start,
    STATE(6), 2,
      sym_glob,
      aux_sym_brace_expansion_repeat1,
    ACTIONS(15), 4,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
    STATE(7), 4,
      sym_brace_expansion,
      sym_integer_range,
      sym_character_choice,
      aux_sym_glob_repeat1,
  [64] = 7,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(37), 1,
      anon_sym_LBRACE,
    ACTIONS(40), 1,
      anon_sym_COMMA,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_glob,
      aux_sym_brace_expansion_repeat1,
    ACTIONS(34), 4,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
    STATE(7), 4,
      sym_brace_expansion,
      sym_integer_range,
      sym_character_choice,
      aux_sym_glob_repeat1,
  [93] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_COMMA,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_glob,
      aux_sym_brace_expansion_repeat1,
    ACTIONS(15), 4,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
    STATE(7), 4,
      sym_brace_expansion,
      sym_integer_range,
      sym_character_choice,
      aux_sym_glob_repeat1,
  [122] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_COMMA,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_glob,
      aux_sym_brace_expansion_repeat1,
    ACTIONS(15), 4,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
    STATE(7), 4,
      sym_brace_expansion,
      sym_integer_range,
      sym_character_choice,
      aux_sym_glob_repeat1,
  [151] = 5,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(53), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(51), 4,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
    STATE(8), 4,
      sym_brace_expansion,
      sym_integer_range,
      sym_character_choice,
      aux_sym_glob_repeat1,
  [174] = 5,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(61), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(58), 4,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
    STATE(8), 4,
      sym_brace_expansion,
      sym_integer_range,
      sym_character_choice,
      aux_sym_glob_repeat1,
  [197] = 5,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(70), 1,
      anon_sym_LBRACE,
    ACTIONS(68), 4,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
    STATE(10), 4,
      sym_brace_expansion,
      sym_integer_range,
      sym_character_choice,
      aux_sym_glob_repeat1,
  [219] = 5,
    ACTIONS(64), 1,
      anon_sym_RBRACK,
    ACTIONS(72), 1,
      anon_sym_LBRACK,
    ACTIONS(78), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 4,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
    STATE(10), 4,
      sym_brace_expansion,
      sym_integer_range,
      sym_character_choice,
      aux_sym_glob_repeat1,
  [241] = 5,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(70), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      sym_glob,
    ACTIONS(81), 4,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
    STATE(9), 4,
      sym_brace_expansion,
      sym_integer_range,
      sym_character_choice,
      aux_sym_glob_repeat1,
  [263] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(11), 1,
      sym_property,
    ACTIONS(85), 1,
      aux_sym__line_token1,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(14), 4,
      sym_comment,
      sym__line,
      sym_pair,
      aux_sym_preamble_repeat1,
  [283] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(11), 1,
      sym_property,
    ACTIONS(89), 1,
      aux_sym__line_token1,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(15), 4,
      sym_comment,
      sym__line,
      sym_pair,
      aux_sym_preamble_repeat1,
  [303] = 5,
    ACTIONS(93), 1,
      aux_sym_comment_token1,
    ACTIONS(96), 1,
      aux_sym__line_token1,
    ACTIONS(99), 1,
      sym_property,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(14), 4,
      sym_comment,
      sym__line,
      sym_pair,
      aux_sym_preamble_repeat1,
  [323] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(11), 1,
      sym_property,
    ACTIONS(85), 1,
      aux_sym__line_token1,
    ACTIONS(102), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(14), 4,
      sym_comment,
      sym__line,
      sym_pair,
      aux_sym_preamble_repeat1,
  [343] = 1,
    ACTIONS(104), 8,
      anon_sym_LBRACK,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [354] = 1,
    ACTIONS(106), 8,
      anon_sym_LBRACK,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [365] = 1,
    ACTIONS(108), 8,
      anon_sym_LBRACK,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [376] = 1,
    ACTIONS(110), 8,
      anon_sym_LBRACK,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [387] = 1,
    ACTIONS(112), 8,
      anon_sym_LBRACK,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [398] = 1,
    ACTIONS(108), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
      anon_sym_LBRACE,
  [408] = 1,
    ACTIONS(110), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
      anon_sym_LBRACE,
  [418] = 1,
    ACTIONS(106), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
      anon_sym_LBRACE,
  [428] = 1,
    ACTIONS(104), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
      anon_sym_LBRACE,
  [438] = 1,
    ACTIONS(112), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SLASH,
      aux_sym_glob_token1,
      sym_wildcard,
      sym_character_escape,
      anon_sym_LBRACE,
  [448] = 1,
    ACTIONS(114), 5,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      aux_sym__line_token1,
      anon_sym_LBRACK,
      sym_property,
  [456] = 4,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    ACTIONS(118), 1,
      anon_sym_LBRACK,
    STATE(13), 1,
      sym_header,
    STATE(27), 2,
      sym_section,
      aux_sym_editorconfig_repeat1,
  [470] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_header,
    STATE(27), 2,
      sym_section,
      aux_sym_editorconfig_repeat1,
  [484] = 4,
    ACTIONS(123), 1,
      anon_sym_RBRACK,
    ACTIONS(125), 1,
      sym_character,
    ACTIONS(128), 1,
      aux_sym_character_choice_token1,
    STATE(29), 2,
      sym_character_range,
      aux_sym_character_choice_repeat1,
  [498] = 4,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
    ACTIONS(133), 1,
      sym_character,
    ACTIONS(135), 1,
      aux_sym_character_choice_token1,
    STATE(29), 2,
      sym_character_range,
      aux_sym_character_choice_repeat1,
  [512] = 4,
    ACTIONS(133), 1,
      sym_character,
    ACTIONS(135), 1,
      aux_sym_character_choice_token1,
    ACTIONS(137), 1,
      anon_sym_RBRACK,
    STATE(29), 2,
      sym_character_range,
      aux_sym_character_choice_repeat1,
  [526] = 4,
    ACTIONS(133), 1,
      sym_character,
    ACTIONS(139), 1,
      anon_sym_BANG,
    ACTIONS(141), 1,
      aux_sym_character_choice_token1,
    STATE(31), 2,
      sym_character_range,
      aux_sym_character_choice_repeat1,
  [540] = 1,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      aux_sym__line_token1,
      anon_sym_LBRACK,
      sym_property,
  [548] = 1,
    ACTIONS(145), 5,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      aux_sym__line_token1,
      anon_sym_LBRACK,
      sym_property,
  [556] = 1,
    ACTIONS(147), 5,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      aux_sym__line_token1,
      anon_sym_LBRACK,
      sym_property,
  [564] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_header,
    STATE(38), 2,
      sym_section,
      aux_sym_editorconfig_repeat1,
  [578] = 4,
    ACTIONS(133), 1,
      sym_character,
    ACTIONS(135), 1,
      aux_sym_character_choice_token1,
    ACTIONS(149), 1,
      anon_sym_RBRACK,
    STATE(29), 2,
      sym_character_range,
      aux_sym_character_choice_repeat1,
  [592] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_header,
    STATE(27), 2,
      sym_section,
      aux_sym_editorconfig_repeat1,
  [606] = 4,
    ACTIONS(133), 1,
      sym_character,
    ACTIONS(135), 1,
      aux_sym_character_choice_token1,
    ACTIONS(153), 1,
      anon_sym_RBRACK,
    STATE(29), 2,
      sym_character_range,
      aux_sym_character_choice_repeat1,
  [620] = 4,
    ACTIONS(133), 1,
      sym_character,
    ACTIONS(155), 1,
      anon_sym_BANG,
    ACTIONS(157), 1,
      aux_sym_character_choice_token1,
    STATE(37), 2,
      sym_character_range,
      aux_sym_character_choice_repeat1,
  [634] = 3,
    ACTIONS(133), 1,
      sym_character,
    ACTIONS(159), 1,
      aux_sym_character_choice_token1,
    STATE(30), 2,
      sym_character_range,
      aux_sym_character_choice_repeat1,
  [645] = 3,
    ACTIONS(163), 1,
      sym_string,
    STATE(35), 1,
      sym__eol,
    ACTIONS(161), 2,
      sym__end_of_file,
      aux_sym__line_token1,
  [656] = 2,
    ACTIONS(167), 1,
      anon_sym_DASH,
    ACTIONS(165), 3,
      anon_sym_RBRACK,
      sym_character,
      aux_sym_character_choice_token1,
  [665] = 3,
    ACTIONS(133), 1,
      sym_character,
    ACTIONS(169), 1,
      aux_sym_character_choice_token1,
    STATE(39), 2,
      sym_character_range,
      aux_sym_character_choice_repeat1,
  [676] = 2,
    STATE(34), 1,
      sym__eol,
    ACTIONS(171), 2,
      sym__end_of_file,
      aux_sym__line_token1,
  [684] = 2,
    STATE(26), 1,
      sym__eol,
    ACTIONS(173), 2,
      sym__end_of_file,
      aux_sym__line_token1,
  [692] = 2,
    STATE(33), 1,
      sym__eol,
    ACTIONS(175), 2,
      sym__end_of_file,
      aux_sym__line_token1,
  [700] = 1,
    ACTIONS(177), 3,
      anon_sym_RBRACK,
      sym_character,
      aux_sym_character_choice_token1,
  [706] = 1,
    ACTIONS(179), 1,
      anon_sym_RBRACK,
  [710] = 1,
    ACTIONS(181), 1,
      aux_sym_integer_range_token1,
  [714] = 1,
    ACTIONS(183), 1,
      aux_sym_pair_token1,
  [718] = 1,
    ACTIONS(185), 1,
      anon_sym_EQ,
  [722] = 1,
    ACTIONS(187), 1,
      aux_sym_character_range_token1,
  [726] = 1,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
  [730] = 1,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
  [734] = 1,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
  [738] = 1,
    ACTIONS(195), 1,
      anon_sym_DOT_DOT,
  [742] = 1,
    ACTIONS(197), 1,
      aux_sym_integer_range_token1,
  [746] = 1,
    ACTIONS(199), 1,
      anon_sym_DOT_DOT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 64,
  [SMALL_STATE(5)] = 93,
  [SMALL_STATE(6)] = 122,
  [SMALL_STATE(7)] = 151,
  [SMALL_STATE(8)] = 174,
  [SMALL_STATE(9)] = 197,
  [SMALL_STATE(10)] = 219,
  [SMALL_STATE(11)] = 241,
  [SMALL_STATE(12)] = 263,
  [SMALL_STATE(13)] = 283,
  [SMALL_STATE(14)] = 303,
  [SMALL_STATE(15)] = 323,
  [SMALL_STATE(16)] = 343,
  [SMALL_STATE(17)] = 354,
  [SMALL_STATE(18)] = 365,
  [SMALL_STATE(19)] = 376,
  [SMALL_STATE(20)] = 387,
  [SMALL_STATE(21)] = 398,
  [SMALL_STATE(22)] = 408,
  [SMALL_STATE(23)] = 418,
  [SMALL_STATE(24)] = 428,
  [SMALL_STATE(25)] = 438,
  [SMALL_STATE(26)] = 448,
  [SMALL_STATE(27)] = 456,
  [SMALL_STATE(28)] = 470,
  [SMALL_STATE(29)] = 484,
  [SMALL_STATE(30)] = 498,
  [SMALL_STATE(31)] = 512,
  [SMALL_STATE(32)] = 526,
  [SMALL_STATE(33)] = 540,
  [SMALL_STATE(34)] = 548,
  [SMALL_STATE(35)] = 556,
  [SMALL_STATE(36)] = 564,
  [SMALL_STATE(37)] = 578,
  [SMALL_STATE(38)] = 592,
  [SMALL_STATE(39)] = 606,
  [SMALL_STATE(40)] = 620,
  [SMALL_STATE(41)] = 634,
  [SMALL_STATE(42)] = 645,
  [SMALL_STATE(43)] = 656,
  [SMALL_STATE(44)] = 665,
  [SMALL_STATE(45)] = 676,
  [SMALL_STATE(46)] = 684,
  [SMALL_STATE(47)] = 692,
  [SMALL_STATE(48)] = 700,
  [SMALL_STATE(49)] = 706,
  [SMALL_STATE(50)] = 710,
  [SMALL_STATE(51)] = 714,
  [SMALL_STATE(52)] = 718,
  [SMALL_STATE(53)] = 722,
  [SMALL_STATE(54)] = 726,
  [SMALL_STATE(55)] = 730,
  [SMALL_STATE(56)] = 734,
  [SMALL_STATE(57)] = 738,
  [SMALL_STATE(58)] = 742,
  [SMALL_STATE(59)] = 746,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_editorconfig, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_brace_expansion_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_brace_expansion_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_brace_expansion_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_brace_expansion_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_brace_expansion_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_glob, 1, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_glob_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_glob_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_glob_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_glob_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_glob_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_glob_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_glob_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preamble, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_choice, 4, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_expansion, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_expansion, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_choice, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer_range, 5, 0, 4),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_editorconfig_repeat1, 2, 0, 0),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_editorconfig_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_editorconfig, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_character_choice_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_choice_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [128] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_character_choice_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 4, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 5, 0, 3),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 4, 0, 1),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_editorconfig, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_character_choice_repeat1, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_range, 3, 0, 2),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [193] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__end_of_file = 0,
  ts_external_token__integer_range_start = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__end_of_file] = sym__end_of_file,
  [ts_external_token__integer_range_start] = sym__integer_range_start,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__end_of_file] = true,
    [ts_external_token__integer_range_start] = true,
  },
  [2] = {
    [ts_external_token__integer_range_start] = true,
  },
  [3] = {
    [ts_external_token__end_of_file] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_editorconfig_external_scanner_create(void);
void tree_sitter_editorconfig_external_scanner_destroy(void *);
bool tree_sitter_editorconfig_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_editorconfig_external_scanner_serialize(void *, char *);
void tree_sitter_editorconfig_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_editorconfig(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_editorconfig_external_scanner_create,
      tree_sitter_editorconfig_external_scanner_destroy,
      tree_sitter_editorconfig_external_scanner_scan,
      tree_sitter_editorconfig_external_scanner_serialize,
      tree_sitter_editorconfig_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "editorconfig",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
