name: Regenerate parser

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  regenerate:
    uses: tree-sitter/workflows/.github/workflows/regenerate.yml@main
    if: >-
      !github.event.repository.is_template &&
      github.actor == 'dependabot[bot]'
